/*
 * AboutDialog.java
 *
 * Created on Pondelok, 2007, marec 26, 10:39
 */

package eu.easyedu.jnetwalk;

/**
 *
 * @author  hlavki
 */
public class AboutDialog extends javax.swing.JDialog {
    
    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        versionTitleLabel = new javax.swing.JLabel();
        authorTitleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        homepageTitleLabel = new javax.swing.JLabel();
        homepageLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTitleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("eu/easyedu/jnetwalk/Bundle"); // NOI18N
        setTitle(bundle.getString("about.menu.item")); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eu/easyedu/jnetwalk/death.gif")));
        iconButton.setBorderPainted(false);
        iconButton.setContentAreaFilled(false);
        iconButton.setFocusPainted(false);
        iconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconButtonActionPerformed(evt);
            }
        });
        getContentPane().add(iconButton);
        iconButton.setBounds(5, 5, 50, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("J");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(69, 14, 10, 29);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel9.setText("NetWalk");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(84, 14, 101, 29);

        versionLabel.setText(bundle.getString("about.dialog.version")); // NOI18N
        getContentPane().add(versionLabel);
        versionLabel.setBounds(140, 60, 230, 15);

        versionTitleLabel.setText(bundle.getString("about.dialog.version.title")); // NOI18N
        getContentPane().add(versionTitleLabel);
        versionTitleLabel.setBounds(20, 60, 110, 15);

        authorTitleLabel.setText(bundle.getString("about.dialog.author.title")); // NOI18N
        getContentPane().add(authorTitleLabel);
        authorTitleLabel.setBounds(20, 80, 110, 15);

        authorLabel.setText(bundle.getString("about.dialog.author")); // NOI18N
        getContentPane().add(authorLabel);
        authorLabel.setBounds(140, 80, 230, 15);

        homepageTitleLabel.setText(bundle.getString("about.dialog.web.title")); // NOI18N
        getContentPane().add(homepageTitleLabel);
        homepageTitleLabel.setBounds(20, 120, 110, 15);

        homepageLabel.setText(bundle.getString("about.dialog.web")); // NOI18N
        getContentPane().add(homepageLabel);
        homepageLabel.setBounds(140, 120, 230, 15);

        emailLabel.setText(bundle.getString("about.dialog.mail")); // NOI18N
        getContentPane().add(emailLabel);
        emailLabel.setBounds(140, 100, 230, 15);

        emailTitleLabel.setText(bundle.getString("about.dialog.mail.title")); // NOI18N
        getContentPane().add(emailTitleLabel);
        emailTitleLabel.setBounds(20, 100, 110, 15);

        jLabel1.setText(bundle.getString("about.dialog.note.title")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 110, 15);

        jTextPane2.setEditable(false);
        jTextPane2.setText(bundle.getString("about.dialog.note")); // NOI18N
        jScrollPane1.setViewportView(jTextPane2);

        jTextPane1.setEditable(false);
        jTextPane1.setText(bundle.getString("about.dialog.note")); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 140, 230, 70);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-391)/2, (screenSize.height-260)/2, 391, 260);
    }// </editor-fold>//GEN-END:initComponents

private void iconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconButtonActionPerformed
    dispose();
}//GEN-LAST:event_iconButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel authorTitleLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailTitleLabel;
    private javax.swing.JLabel homepageLabel;
    private javax.swing.JLabel homepageTitleLabel;
    private javax.swing.JButton iconButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel versionTitleLabel;
    // End of variables declaration//GEN-END:variables
    
}
